[package]
name = "nightowl"
version = "0.1.0"
edition = "2024"
license = "AGPL-3.0-only"
description = "Kubernetes operator for Apache Fluss (FlussCluster)"

[dependencies]
fluss-rs = { version = "1.0.0", git = "https://github.com/midnattsol/fluss.git", rev = "218ff0897db9dde34552f941276c281bbcb23be4" }
chrono = "0.4"
kube = { version = "4.2", features = ["derive", "runtime"] }
k8s-openapi = { version = "0.28", features = ["v1_32", "schemars"] }
schemars = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.10"
tokio = { version = "1", features = ["full"] }
futures = "0.3"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
thiserror = "2"

[dev-dependencies]
serde_yaml = "0.9"
