[book]
title = "Owl"
description = "Operate Apache Fluss on Kubernetes with Owl"
language = "en"
src = "en"

[build]
build-dir = "../target/book/en"
create-missing = false

[output.html]
theme = "theme"
default-theme = "light"
preferred-dark-theme = "coal"
additional-css = ["theme/custom.css"]
additional-js = ["theme/language.js"]
no-section-label = true
sidebar-header-nav = false

[output.html.playground]
runnable = false
